const ExerciseList = {
  Overview: "Tổng quan",
  Class: "Lớp học",
  Document: "Học liệu",
  TrainingMISAEMIS: "Đào tạo MISA EMIS",
  Hello: "Xin chào",
  Setting: "Thiết lập",
  Help: "Trợ giúp",
  Alert: "Thông báo",
  FormalClass: "Lớp chính quy",
  ExtraClass: "Lớp học thêm",
  PositiveTeacher: "GIÁO VIÊN TÍCH CỰC",
  DocEditer: "Học liệu đã soạn",
  DocShared: "Học liệu đã chia sẻ",
  DocUser: "Người sử dụng học liệu",
  NotFoundData: "Không có kết quả phù hợp",
  AddInfor: "Bổ sung thông tin",
  ChangeType: "Đổi kiểu soạn",
  Try: "Làm thử",
  Done: "Hoàn thành",
  AutoCreate: "Tách câu hỏi tự động sử dụng công nghệ AI",
  SisapComunication: "Cộng đồng giáo viên SISAP Ôn tập",
  TeacherShare: "Thầy cô chia sẻ thắc mắc đến",
  Supported: "để nhận được hỗ trợ nhé!",
  CreateQuestion: "hoặc tự tạo câu hỏi mới",
  True: "Đúng",
  False: "Sai",
  MarkAnswer: "Đánh dấu đáp án đúng",
  EmisTranining: "EMIS Ôn tập",
  Agree: "Đồng ý",
  Grade: "Khối",
  Watch: "Xem",
  Delete: "Xóa",
};
export default ExerciseList;
